### ISSUE TITLE
The macro pack is empty on linux

### ISSUE THREAD

**Issue by xdy** [IsThisMyRealName/too-many-tokens-pf#2]
This is because the 'packs' folder is actually named 'Packs' on the file system. I confirmed this by moving all the files from the Packs folder to the packs folder, which made the macros work. (too-many-tokens-dnd has the same problem.)

One way to fix this is to do the following on your command line and then pushing your changes:
`
git mv Packs packs.tmp
git mv packs.tmp packs
` 
(Needs to be in two steps on windows as windows is not case sensitive.)

**Comment by IsThisMyRealName** [comment]
Oh, i did not realize that. Your proposed changes should be in the newest version. I hope it works now and will change that for tmt-dnd and tmt-online soon. I suspect that might be responsible for most issues I could not reproduce. Thank you for your feedback!

**Comment by xdy** [comment]
You're not the first git user to get hit by that problem. Heck, you're not the first developer in this conversation to get hit by it. :)

Anyway, 1.0.1 does indeed work well for me.
